package com.syeedode.authentication;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;


@RunWith(SpringRunner.class)
@SpringBootTest
public class AuthenticationServicesTest {
    @Test
    public void contextLoads() {
        // com.syeedode.authentication.AuthenticationServices classUnderTest = new com.syeedode.authentication.AuthenticationServices();
    }
}
