package com.syeedode.authentication;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
public class AuthenticationServices {
    public static void main(String[] args) {
        SpringApplication.run(AuthenticationServices.class, args);
    }
}
